# Build configuration for code generation
targets:
  $default:
    builders:
      injectable_generator:injectable_builder:
        enabled: true
        options:
          auto_register: true
          # Generate config in the same directory as the injection.dart file

      json_serializable:
        enabled: true
        options:
          any_map: false
          checked: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: true
          field_rename: snake
          include_if_null: false
