// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl562ja4GL93iPzJjoNMd3uUoFArnsAZ8',
    appId: '1:847594938127:web:c9fcd3f0eeb7b9a59c287a',
    messagingSenderId: '847594938127',
    projectId: 'copdiary-9d75b',
    authDomain: 'copdiary-9d75b.firebaseapp.com',
    storageBucket: 'copdiary-9d75b.firebasestorage.app',
    measurementId: 'G-XTLGVY9WQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIVsZTmOMAzLC58spP5cQqFchIM3Eb3Yo',
    appId: '1:847594938127:android:fc3f2da64f9b306e9c287a',
    messagingSenderId: '847594938127',
    projectId: 'copdiary-9d75b',
    storageBucket: 'copdiary-9d75b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUn4HsIXTg98q2fVK0sW46TJW1y7GpVHY',
    appId: '1:847594938127:ios:0a715053ff7344c59c287a',
    messagingSenderId: '847594938127',
    projectId: 'copdiary-9d75b',
    storageBucket: 'copdiary-9d75b.firebasestorage.app',
    iosBundleId: 'com.diary.copdiary',
  );
}
